spring:
  application:
    name: todo-in-spring

  datasource:
    url: jdbc:postgresql://localhost:5432/tododb
    username: postgres
    password: 123456

  jpa:
    hibernate:
      ddl-auto: none

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
